<?php $config = array (
  'STORE_NAME' => 
  array (
    'en' => 'Illuminata Eyewear',
  ),
  'STORE_HEADLINE' => 
  array (
    'en' => '',
  ),
  'TITLE_SEPARATOR' => '|',
  'TITLE_FORMAT' => 'NAME_FIRST',
  'DEFAULT_META_DESCR' => 
  array (
    'en' => 'Glasses Store in Etobicoke and Online Glasses Store. Huge Selection of Brand Name Glasses, Sunglasses, Contact Lenses. Full Eye Exam only $65. Dior, Gucci, Prada, Tiffany, Tory Burch, Hugo Boss, Tom Ford, Roberto Cavalli, OGA, Burberry, Bvlgari, Etnia, Carrera, Marc Jacobs',
  ),
  'LOGO' => 'upload/LOGO-logo500px.PNG',
  'FAVICON' => 'upload/FAVICON-favIcon.PNG',
  'THEME' => 'IlluminataV3',
  'DISABLE_AJAX' => 1,
  'NUM_NEWS_INDEX' => 6,
  'HOME_PAGE_SUBCATS' => 1,
  'INDEX_MAN_FILTERS' => 1,
  'INDEX_PRICE_FILTERS' => 1,
  'INDEX_META_DESCRIPTION' => 
  array (
    'en' => 'Brand name eyeglasses from Toronto privately owned boutique. Pick up in store or ship worldwide. Prada, Gucci, Dior, Tom Ford, Burberry, Roberto Cavalli, Bulgari, Tiffany, Versace, Hugo Boss and 30+ more brands',
  ),
  'INDEX_META_KEYWORDS' => 
  array (
    'en' => 'eyeglasses online, eyeglasses store in Etobicoke, Prada eyeglasses, Gucci sunglasses, Dior glasses, Tom Ford sunglasses, Burberry sunglasses, Roberto Cavalli sunglasses, Bulgari glasses, Tiffany sunglasses, Versace glasses, Hugo Boss eyeglasses',
  ),
  'HIDE_SUBCATS' => 0,
  'CATEGORY_COLUMNS' => 2,
  'CATEGORY_COL_DIRECTION' => 'CAT_VER',
  'CAT_MENU_IMAGE' => 1,
  'CAT_MENU_DESCR' => 0,
  'CAT_MENU_SUBS' => 3,
  'ALLOWED_SORT_ORDER' => 
  array (
    'FEATURED' => '1',
    'SALES_RANK' => '1',
    'RATING' => '1',
    'PRODUCT_NAME_ASC' => '1',
    'PRODUCT_NAME_DESC' => '1',
    'PRICE_ASC' => '1',
    'PRICE_DESC' => '1',
    'NEWEST_ARRIVALS' => '1',
  ),
  'SORT_ORDER' => 'NEWEST_ARRIVALS',
  'DISPLAY_NUM_CAT' => 0,
  'DISPLAY_PRICES' => 1,
  'DISPLAY_CATEGORY_DESC' => 1,
  'INCLUDE_SUBCATEGORY_PRODUCTS' => 0,
  'FEATURED_COUNT' => 10,
  'FEATURED_RANDOM' => 1,
  'DISPLAY_CATEGORY_FEATURED' => 0,
  'FEATURED_LAYOUT' => '',
  'LIST_LAYOUT' => 'GRID',
  'ENABLED_LIST_LAYOUTS' => 
  array (
    'LIST' => '1',
    'GRID' => '1',
    'TABLE' => '1',
  ),
  'NUM_PRODUCTS_PER_CAT' => 10,
  'LAYOUT_GRID_COLUMNS' => 3,
  'LAYOUT_GRID_ROWS' => 5,
  'ALLOW_SWITCH_LAYOUT' => 1,
  'TABLE_VIEW_COLUMNS' => 
  array (
    'IMAGE' => '1',
    'SKU' => '1',
    'NAME' => '1',
    'PRICE' => '1',
    'DETAILS' => '1',
  ),
  'MISSING_IMG_THUMB' => 'upload/MISSING_IMG_THUMB-noImageSmall.JPG',
  'MISSING_IMG_SMALL' => 'upload/MISSING_IMG_SMALL-noImageMedium.JPG',
  'MISSING_IMG_LARGE' => 'upload/MISSING_IMG_LARGE-noImageLarge.JPG',
  'DISPLAY_NUM_FILTER' => 1,
  'ENABLE_MAN_FILTERS' => 1,
  'ENABLE_PRICE_FILTERS' => 1,
  'DISPLAY_CAT_MAN_FILTERS' => 1,
  'DISPLAY_CAT_PRICE_FILTERS' => 1,
  'validate_NUM_PRODUCTS_PER_CAT' => 'MinValueCheck: <1: _err_not_positive>',
  'PRODUCT_TABS' => 0,
  'INCLUDE_BASE_TAXES' => 1,
  'SHOW_PRODUCT_WEIGHT' => 0,
  'SHOW_SKU_CART' => 0,
  'SHOW_SKU_EMAIL' => 1,
  'UNIT_SYSTEM' => 'METRIC',
  'QUANT_FIELD_TYPE' => 'QUANT_SELECT',
  'PRODUCT_PAGE_LIST_LAYOUT' => '',
  'PRODUCT_DISPLAY_STOCK' => 0,
  'PRODUCT_DISPLAY_LOW_STOCK' => 0,
  'PRODUCT_DISPLAY_NO_STOCK' => 0,
  'LOW_STOCK' => 5,
  'NUM_PURCHASED_TOGETHER' => 5,
  'ENABLE_PRODUCT_COMPARE' => 0,
  'PRODUCT_INQUIRY_FORM' => 1,
  'ENABLE_REVIEWS' => 1,
  'ENABLE_RATINGS' => 1,
  'REVIEWS_WITH_RATINGS' => 1,
  'REQUIRE_PURCHASE_TO_RATE' => 0,
  'ENABLE_ANONYMOUS_RATINGS' => 0,
  'RATING_SCALE' => 5,
  'RATING_SAME_IP_TIME' => 24,
  'APPROVE_REVIEWS' => 'APPROVE_REVIEWS_USER',
  'NUM_REVIEWS_IN_PRODUCT_PAGE' => 2,
  'REVIEWS_PER_PAGE' => 5,
  'validate_LOW_STOCK' => 'MinValueCheck: <1: _err_not_positive>',
  'MAX_FILTER_CRITERIA_COUNT' => 5,
  'FILTER_STYLE' => 'FILTER_STYLE_LINKS',
  'TOP_MENU_COMPACT' => 0,
  'TOP_FILTER_PRICE' => 0,
  'TOP_FILTER_MANUFACTURER' => 0,
  'TOP_FILTER_CONTINUOS' => 0,
  'TOP_FILTER_RELOAD' => 1,
  'PRICE_FILTER_NAME_1' => 
  array (
    'en' => '0 to 24',
  ),
  'PRICE_FILTER_FROM_1' => 0,
  'PRICE_FILTER_TO_1' => 24,
  'PRICE_FILTER_NAME_2' => 
  array (
    'en' => '25 to 49',
  ),
  'PRICE_FILTER_FROM_2' => 25,
  'PRICE_FILTER_TO_2' => 49,
  'PRICE_FILTER_NAME_3' => 
  array (
    'en' => '50 to 99',
  ),
  'PRICE_FILTER_FROM_3' => 50,
  'PRICE_FILTER_TO_3' => 99,
  'PRICE_FILTER_NAME_4' => 
  array (
    'en' => '100 to 199',
  ),
  'PRICE_FILTER_FROM_4' => 100,
  'PRICE_FILTER_TO_4' => 199,
  'PRICE_FILTER_NAME_5' => 
  array (
    'en' => '200 to 499',
  ),
  'PRICE_FILTER_FROM_5' => 200,
  'PRICE_FILTER_TO_5' => 499,
  'PRICE_FILTER_NAME_6' => 
  array (
    'en' => '500 to 999',
  ),
  'PRICE_FILTER_FROM_6' => 500,
  'PRICE_FILTER_TO_6' => 999,
  'PRICE_FILTER_NAME_7' => 
  array (
    'en' => '1000 to 1999',
  ),
  'PRICE_FILTER_FROM_7' => 1000,
  'PRICE_FILTER_TO_7' => 1999,
  'PRICE_FILTER_NAME_8' => 
  array (
    'en' => '2000 to 4999',
  ),
  'PRICE_FILTER_FROM_8' => 2000,
  'PRICE_FILTER_TO_8' => 4999,
  'PRICE_FILTER_NAME_9' => 
  array (
    'en' => '5000 to 9999',
  ),
  'PRICE_FILTER_FROM_9' => 5000,
  'PRICE_FILTER_TO_9' => 9999,
  'PRICE_FILTER_NAME_10' => 
  array (
    'en' => 'More than 10000',
  ),
  'PRICE_FILTER_FROM_10' => 10000,
  'PRICE_FILTER_TO_10' => '10000000000.00',
  'USER_COUNT_RECENT_ORDERS' => 2,
  'USER_ORDERS_PER_PAGE' => 5,
  'IMAGE_DOMAIN' => '',
  'ENABLE_WATERMARKS' => 0,
  'WATERMARK_IMAGE' => 'upload/WATERMARK_IMAGE-watermark.PNG',
  'WATERMARK_POSITION' => 'BOTTOM_LEFT',
  'WATERMARK_X' => 10,
  'WATERMARK_Y' => 10,
  'IMG_P_W_1' => 100,
  'IMG_P_H_1' => 60,
  'IMG_P_Q_1' => 80,
  'IMG_P_W_2' => 200,
  'IMG_P_H_2' => 140,
  'IMG_P_Q_2' => 80,
  'IMG_P_W_3' => 400,
  'IMG_P_H_3' => 300,
  'IMG_P_Q_3' => 80,
  'IMG_P_W_4' => 800,
  'IMG_P_H_4' => 600,
  'IMG_P_Q_4' => 80,
  '_ENLARGE_PRODUCT_THUMBNAILS_ON' => 'P_THUMB_ENLARGE_CLICK',
  'IMG_C_W_1' => 80,
  'IMG_C_H_1' => 50,
  'IMG_C_Q_1' => 80,
  'IMG_C_W_2' => 120,
  'IMG_C_H_2' => 80,
  'IMG_C_Q_2' => 80,
  'IMG_C_W_3' => 400,
  'IMG_C_H_3' => 300,
  'IMG_C_Q_3' => 80,
  'IMG_C_W_4' => 800,
  'IMG_C_H_4' => 600,
  'IMG_C_Q_4' => 80,
  'IMG_M_W_1' => 80,
  'IMG_M_H_1' => 50,
  'IMG_M_Q_1' => 80,
  'IMG_M_W_2' => 120,
  'IMG_M_H_2' => 80,
  'IMG_M_Q_2' => 80,
  'IMG_M_W_3' => 400,
  'IMG_M_H_3' => 300,
  'IMG_M_Q_3' => 80,
  'IMG_M_W_4' => 800,
  'IMG_M_H_4' => 600,
  'IMG_M_Q_4' => 80,
  'IMG_O_W_1' => 80,
  'IMG_O_H_1' => 50,
  'IMG_O_Q_1' => 80,
  'IMG_O_W_2' => 600,
  'IMG_O_H_2' => 400,
  'IMG_O_Q_2' => 80,
  'validate_IMG_P_W_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_H_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_Q_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_W_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_H_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_Q_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_W_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_H_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_Q_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_W_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_H_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_Q_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_W_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_H_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_Q_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_W_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_H_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_Q_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_W_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_H_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_Q_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_W_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_H_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_Q_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_W_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_H_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_Q_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_W_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_H_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_Q_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_W_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_H_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_Q_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_W_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_H_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_Q_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_W_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_H_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_Q_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_W_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_H_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_Q_2' => 'MinValueCheck: <1: _err_not_positive>',
  'CATEGORY_MENU_TYPE' => 'CAT_MENU_STANDARD',
  'CAT_MENU_LEFT_ROOT' => 107,
  'CAT_MENU_TOP_ROOT' => 230,
  'TOP_MENU_HIDE' => 0,
  'TOP_MENU_HIDE_CATS' => 0,
  'LANG_SELECTION' => 'LANG_NAMES',
  'HIDE_SEARCH_CATS' => 1,
  'SALE_ITEMS_COUNT' => 5,
  'NEWEST_ITEMS_COUNT' => 5,
  'BESTSELLING_ITEMS_COUNT' => 5,
  'BESTSELLING_ITEMS_DAYS' => 30,
  'INVOICE_SELLER_INFO' => 
  array (
    'en' => 'Illuminata Eyewear<br />1750 The Queensway<br />Etobicoke, ON<br />M9C 5H5<br /><br />Tel. 416-620-8028',
  ),
  'INVOICE_LOGO' => 'upload/INVOICE_LOGO-logoInvoice.PNG',
  'DISABLE_INVOICES' => 0,
  'INVOICE_SHOW_PAYMENT_INFO' => 1,
  'SHIP_LABELS_PER_ROW' => 2,
  'SHIP_LABELS_REPEAT' => 1,
  'SHIP_LABELS_COPIES' => 1,
  'NUMBER_OF_PRODUCTS_TO_INCLUDE' => 100,
  'NUMBER_OF_NEWS_POSTS_TO_INCLUDE' => 10,
  'ENABLED_FEEDS' => 
  array (
    'ALL_PRODUCTS' => 1,
    'CATEGORY_PRODUCTS' => 1,
    'NEWS_POSTS' => 1,
  ),
  'INVENTORY_TRACKING' => 'ENABLE_AND_DISPLAY',
  'INVENTORY_TRACKING_DOWNLOADABLE' => 0,
  'REQUIRE_PHONE' => 1,
  'REQUIRE_REG_ADDRESS' => 0,
  'REG_EMAIL_CONFIRM' => 0,
  'DISABLE_STATE' => 0,
  'PASSWORD_GENERATION' => 'PASSWORD_REQUIRE',
  'USER_FIELDS' => 
  array (
    'FIRSTNAME' => '1',
    'LASTNAME' => '1',
    'COMPANYNAME' => '1',
    'PHONE' => '1',
    'ADDRESS1' => '1',
    'ADDRESS2' => '1',
    'CITY' => '1',
    'COUNTRY' => '1',
    'STATE' => '1',
    'POSTALCODE' => '1',
  ),
  'PRIMARY_COUNTRIES' => 'US, CA',
  'ENABLED_COUNTRIES' => 
  array (
    'AU' => '1',
    'AT' => '1',
    'BE' => '1',
    'VG' => '1',
    'CA' => '1',
    'CN' => '1',
    'DK' => '1',
    'FI' => '1',
    'FR' => '1',
    'DE' => '1',
    'GR' => '1',
    'HK' => '1',
    'HU' => '1',
    'IS' => '1',
    'IE' => '1',
    'IL' => '1',
    'IT' => '1',
    'LI' => '1',
    'MC' => '1',
    'NL' => '1',
    'NZ' => '1',
    'PL' => '1',
    'PT' => '1',
    'SG' => '1',
    'ES' => '1',
    'CH' => '1',
    'GB' => '1',
    'US' => '1',
  ),
  'ENABLE_CART' => 1,
  'ENABLE_WISHLISTS' => 1,
  'MIN_TOTAL' => '',
  'MAX_TOTAL' => '',
  'MIN_QUANT' => '',
  'MAX_QUANT' => '',
  'CHECKOUT_METHOD' => 'CHECKOUT_ONEPAGE',
  'DISABLE_GUEST_CHECKOUT' => 0,
  'DISABLE_GUEST_CART' => 0,
  'SKIP_CART' => 0,
  'SKIP_SHIPPING' => 1,
  'SKIP_PAYMENT' => 1,
  'CHECKOUT_CUSTOM_FIELDS' => 'CART_PAGE',
  'ENABLE_MULTIADDRESS' => 0,
  'REQUIRE_SAME_ADDRESS' => 0,
  'DISABLE_CHECKOUT_ADDRESS_STEP' => 0,
  'ENABLE_CHECKOUTDELIVERYSTEP' => 0,
  'OPC_SHOW_CART' => 0,
  'REQUIRE_TOS' => 0,
  'TOS_MESSAGE' => 
  array (
    'en' => 'I agree to the Terms of the Service',
  ),
  'TOS_OPC_ONLY' => 0,
  'HIDE_TAXES' => 0,
  'INVOICE_NUMBER_GENERATOR' => 'SequentialInvoiceNumber',
  'SequentialInvoiceNumber_START_AT' => 3000,
  'SequentialInvoiceNumber_STEP' => 1,
  'SequentialInvoiceNumber_MIN_LENGTH' => 5,
  'SequentialInvoiceNumber_PREFIX' => 'IL',
  'SequentialInvoiceNumber_SUFFIX' => '',
  'ENABLE_SHIPPING_ESTIMATE' => 1,
  'SHIP_ESTIMATE_HIDE_ENTRY' => '',
  'SHIP_ESTIMATE_FIELDS' => 
  array (
    'COUNTRY' => '1',
    'STATE' => '1',
  ),
  'OFFLINE_HANDLERS' => '',
  'CC_ENABLE' => 0,
  'REQUIRE_CVV' => 1,
  'CC_AUTHONLY' => 1,
  'CC_HANDLER' => 'TestCreditCard',
  'EXPRESS_HANDLERS' => '',
  'PAYMENT_HANDLERS' => 
  array (
    'Beanstream' => '1',
    'PaypalWebsitePaymentsStandard' => '1',
  ),
  'AlertPay_EMAIL' => 'info@integry.net',
  'AlertPay_SECURITY_CODE' => '',
  'AlertPay_ITEM_NAME' => 'Shopping cart items',
  'AurigaePayment_merchant' => 11111,
  'AurigaePayment_md5' => '',
  'AurigaePayment_method' => 'KORTINSE',
  'AurigaePayment_test' => 0,
  'AuthorizeNet_login' => 'cnpdev4444',
  'AuthorizeNet_transactionKey' => 'zzzzzz6Pj3Pz6',
  'AuthorizeNet_gateway' => 'https://secure.authorize.net/gateway/transact.dll',
  'AuthorizeNetSIM_login' => '',
  'AuthorizeNetSIM_transKey' => '',
  'AuthorizeNetSIM_test' => 0,
  'Beanstream_merchant_id' => '343180001',
  'Beanstream_hash' => 'HASH-tag-Bean',
  'BeanstreamCC_merchant_id' => '271090000',
  'BeanstreamCC_hash' => 'bean-STREAM-hash',
  'BucksNet_username' => '',
  'BucksNet_password' => '',
  'BucksNet_traderID' => '',
  'BucksNet_vatID' => '',
  'BucksNet_test' => 0,
  'CCAvenue_Merchant_Id' => '',
  'CCAvenue_WorkingKey' => '',
  'CCAvenue_Currency' => 'INR',
  'CCNow_login' => '',
  'CCNow_key' => '',
  'ChronoPayGateway_productid' => '',
  'ChronoPayGateway_secret' => '',
  'CyberMUT_TPE' => '',
  'CyberMUT_societe' => '',
  'CyberMUT_key1' => '',
  'CyberMUT_key2' => '',
  'CyberMUT_bank' => 'CyberMUT_CM',
  'CyberMUT_test' => 0,
  'DibsFlexWin_merchant' => 11111,
  'DibsFlexWin_md51' => '',
  'DibsFlexWin_md52' => '',
  'DibsFlexWin_test' => 0,
  'EWayCvn_customerID' => '87654321',
  'EWayCvn_invoiceDescription' => '',
  'EWayCvn_test' => 0,
  'GTBill_MerchantID' => '',
  'GTBill_SiteID' => '',
  'GoogleCheckout_sandbox' => 0,
  'GoogleCheckout_merchant_id' => '',
  'GoogleCheckout_merchant_key' => '',
  'HsbcPci_client' => '',
  'HsbcPci_key' => '',
  'HsbcPci_currency' => '',
  'HsbcPci_capture_automatically' => 1,
  'HsbcPci_test' => 0,
  'InternetSecureMerchantLink_account' => 1234,
  'InternetSecureMerchantLink_test' => 0,
  'MoneyBookers_email' => '',
  'MoneyBookers_secretWord' => '',
  'OFFLINE_NAME_1' => 
  array (
    'en' => 'Bank Wire Transfer',
  ),
  'OFFLINE_LOGO_1' => false,
  'OFFLINE_DESCR_1' => 
  array (
    'en' => 'You can pay for your order via bank wire transfer',
  ),
  'OFFLINE_INSTR_1' => 
  array (
    'en' => 'Please transfer the money to our account AB123456 and do not forget to quote the order ID',
  ),
  'OFFLINE_NAME_2' => 
  array (
    'en' => 'Additional Offline Payment Method',
  ),
  'OFFLINE_LOGO_2' => false,
  'OFFLINE_DESCR_2' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_2' => 
  array (
    'en' => '',
  ),
  'OFFLINE_NAME_3' => 
  array (
    'en' => 'Another Offline Payment Method',
  ),
  'OFFLINE_LOGO_3' => false,
  'OFFLINE_DESCR_3' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_3' => 
  array (
    'en' => '',
  ),
  'OFFLINE_NAME_4' => 
  array (
    'en' => 'Offline method 4',
  ),
  'OFFLINE_LOGO_4' => false,
  'OFFLINE_DESCR_4' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_4' => 
  array (
    'en' => '',
  ),
  'OFFLINE_NAME_5' => 
  array (
    'en' => 'Offline method 5',
  ),
  'OFFLINE_LOGO_5' => false,
  'OFFLINE_DESCR_5' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_5' => 
  array (
    'en' => '',
  ),
  'OFFLINE_NAME_6' => 
  array (
    'en' => 'Offline method 6',
  ),
  'OFFLINE_LOGO_6' => false,
  'OFFLINE_DESCR_6' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_6' => 
  array (
    'en' => '',
  ),
  'OfflineCreditCard_customCardTypes' => '',
  'OfflineCreditCard_cardTypes' => 
  array (
    'American Express' => 1,
    'Discover Card' => 1,
    'MasterCard' => 1,
    'Visa' => 1,
  ),
  'Ogone_pspid' => '',
  'Ogone_secretWord' => '',
  'Ogone_test' => 0,
  'PayMate_mid' => '',
  'PayMate_test' => 0,
  'PayPointLite_merchant' => '',
  'PayPointLite_remotepassword' => '',
  'PayPointLite_digestkey' => '',
  'PayPointLite_currency' => 'GBP',
  'PaypalDirectPayment_sandbox' => 0,
  'PaypalDirectPayment_username' => 'sandbox_api1.integry.net',
  'PaypalDirectPayment_password' => '9AURFxxxxxxxxXV',
  'PaypalDirectPayment_signature' => 'AeQ618dBMNS1xxxxxxxxxxxxxxoPUhcIj1J5p65ZAR8Pu',
  'PaypalDirectPayment_cardTypes' => 
  array (
    'Visa' => 1,
    'MasterCard' => 1,
    'American Express' => 1,
    'Discover' => 1,
  ),
  'PaypalExpressCheckout_sandbox' => 0,
  'PaypalExpressCheckout_username' => 'sandbox_api1.integry.net',
  'PaypalExpressCheckout_password' => '9AURF7SxxxxxxxxxxXV',
  'PaypalExpressCheckout_signature' => 'AeQ618dBxxxxxxxxxxxxxxxxxnzBekoPUhcIj1J5p65ZAR8Pu',
  'PaypalExpressCheckout_AUTHONLY' => 0,
  'PaypalWebsitePaymentsStandard_EMAIL' => 'sales@illuminataeyewear.com',
  'PaypalWebsitePaymentsStandard_SANDBOX' => 0,
  'PaypalWebsitePaymentsStandard_DEF_CURRENCY' => 'CAD',
  'ProtxForm_vendor' => '',
  'ProtxForm_description' => '',
  'ProtxForm_key' => '',
  'ProtxForm_mode' => 'PROTX_LIVE',
  'SaferPay_ACCOUNTID' => '99867-94913159',
  'SaferPay_DESCRIPTION' => 'Submit payment for your order',
  'TwoCheckout_account' => '477167',
  'TwoCheckout_currency' => 'USD',
  'TwoCheckout_secretWord' => 'tango',
  'TwoCheckout_test' => 0,
  'TwoCheckoutINS_account' => '477167',
  'TwoCheckoutINS_currency' => 'USD',
  'TwoCheckoutINS_secretWord' => 'tango',
  'TwoCheckoutINS_test' => 0,
  'VCS_account' => 1111,
  'VCS_description' => '',
  'WebToPay_merchantid' => '',
  'WebToPay_projectid' => '',
  'WebToPay_signaturepassword' => '',
  'WebToPay_country' => '',
  'WebToPay_test' => 0,
  'WorldPayHostedPaymentPage_account' => '',
  'WorldPayHostedPaymentPage_test' => 0,
  'ewayshared_customerID' => '87654321',
  'ewayshared_userName' => '',
  'ewayshared_invoiceDescription' => '',
  'ewayshared_country' => 'EWAY_NZ',
  'iDEALeasy_bank' => 'ABN-AMRO',
  'iDEALeasy_account' => 'TESTiDEALEASY',
  'iDEALeasy_description' => '',
  'CanadaPostShipping_merchantID' => '',
  'FedexShipping_accountNumber' => '',
  'FedexShipping_meterNumber' => '',
  'FedexShipping_apiUrl' => 'https://gatewaybeta.fedex.com/GatewayDC',
  'FedexShipping_enabledServices' => 
  array (
    'PRIORITYOVERNIGHT' => 1,
    'STANDARDOVERNIGHT' => 1,
    'FIRSTOVERNIGHT' => 1,
    'FEDEX2DAY' => 1,
    'FEDEXEXPRESSSAVER' => 1,
    'INTERNATIONALPRIORITY' => 1,
    'INTERNATIONALECONOMY' => 1,
    'INTERNATIONALFIRST' => 1,
    'FEDEX1DAYFREIGHT' => 1,
    'FEDEX2DAYFREIGHT' => 1,
    'FEDEX3DAYFREIGHT' => 1,
    'FEDEXGROUND' => 1,
    'GROUNDHOMEDELIVERY' => 1,
  ),
  'UpsShipping_accessKey' => '',
  'UpsShipping_user' => '',
  'UpsShipping_password' => '',
  'UpsShipping_enabledServices' => 
  array (
    'UPS01' => 1,
    'UPS02' => 1,
    'UPS03' => 1,
    'UPS07' => 1,
    'UPS08' => 1,
    'UPS11' => 1,
    'UPS12' => 1,
    'UPS13' => 1,
    'UPS14' => 1,
    'UPS54' => 1,
    'UPS59' => 1,
    'UPS65' => 1,
  ),
  'UspsShipping_userId' => '',
  'UspsShipping_apiUrl' => 'http://production.shippingapis.com/ShippingAPI.dll',
  'UspsShipping_domestic' => 
  array (
    'First Class' => 1,
    'Express' => 1,
    'Priority' => 1,
  ),
  'UspsShipping_size' => '',
  'UspsShipping_priorityPackageType' => '',
  'UspsShipping_isMachinable' => 1,
  'UspsShipping_international' => 
  array (
  ),
  'TRACKING_SERVICES' => 
  array (
  ),
  'GoogleAnalytics_code' => 'UA-123456',
  'FEED_KEY' => '',
  'ENABLE_SITEMAPS' => 1,
  'HTML_EMAIL' => 1,
  'NOTIFY_NEW_ORDER' => 1,
  'NOTIFY_NEW_NOTE' => 1,
  'NOTIFICATION_EMAIL' => 'info@liveoptical.com, sales@illuminataeyewear.com',
  'EMAIL_NEW_USER' => 1,
  'EMAIL_NEW_ORDER' => 1,
  'EMAIL_STATUS_UPDATE' => 1,
  'EMAIL_STATUS_UPDATE_STATUSES' => 
  array (
    'EMAIL_STATUS_UPDATE_NEW' => '1',
    'EMAIL_STATUS_UPDATE_PROCESSING' => '1',
    'EMAIL_STATUS_UPDATE_AWAITING_SHIPMENT' => '1',
    'EMAIL_STATUS_UPDATE_SHIPPED' => '1',
  ),
  'EMAIL_ORDER_CANCELLATION' => 1,
  'EMAIL_ORDERNOTE' => 1,
  'MAIN_EMAIL' => 'sales@illuminataeyewear.com',
  'NEWSLETTER_EMAIL' => 'sales@illuminataeyewear.com',
  'EMAIL_METHOD' => 'MAIL_NATIVE',
  'SMTP_SERVER' => '',
  'SMTP_PORT' => 25,
  'SMTP_USERNAME' => '',
  'SMTP_PASSWORD' => '',
  'UPDATE_COPY_METHOD' => 'UPDATE_FTP',
  'UPDATE_FTP_SERVER' => '',
  'UPDATE_FTP_USER' => '',
  'UPDATE_FTP_PASSWORD' => '',
  'UPDATE_FTP_DIRECTORY' => 'public_html',
  'UPDATE_REPO_1' => 'http://repo.livecart.com',
  'UPDATE_REPO_2' => 'http://extra.livecart.com',
  'UPDATE_REPO_3' => 'http://trial.livecart.com',
  'UPDATE_REPO_4' => '',
  'UPDATE_REPO_5' => '',
  'UPDATE_REPO_6' => '',
  'UPDATE_REPO_7' => '',
  'UPDATE_REPO_8' => '',
  'UPDATE_REPO_9' => '',
  'UPDATE_REPO_10' => '',
  'UPDATE_REPO_11' => '',
  'UPDATE_REPO_12' => '',
  'UPDATE_REPO_13' => '',
  'UPDATE_REPO_14' => '',
  'UPDATE_REPO_15' => '',
  'UPDATE_REPO_16' => '',
  'UPDATE_REPO_17' => '',
  'UPDATE_REPO_18' => '',
  'UPDATE_REPO_19' => '',
  'UPDATE_REPO_20' => '',
  'SSL_PAYMENT' => 0,
  'SSL_CHECKOUT' => 0,
  'SSL_CUSTOMER' => 0,
  'SSL_BACKEND' => 0,
  'SSL_DOMAIN' => '',
  'AUTO_GENERATE_SKU' => 0,
  'DEFAULT_PRODUCT_ENABLED' => 1,
  'DEFAULT_PRODUCT_TYPE' => '_prod_type_0',
  'SHOW_BACKEND_LANG_FILES' => 0,
  'SHOW_BACKEND_TEMPLATE_FILES' => 0,
  'DISABLE_WYSIWYG' => 0,
  'DISABLE_TOOLBAR' => 0,
  'DISABLE_QUICKEDIT' => 1,
  'URL_REPLACE_SPECIAL_CHARS' => 1,
  'URL_301_AUTO_REDIRECT' => 1,
  'CACHE_METHOD' => 'FileCache',
  'PROXY_HOST' => '',
  'PROXY_PORT' => 0,
  'USE_DEFAULT_SESSION_HANDLER' => 0,
  'API_AUTH_METHODS' => 
  array (
    'ApiAuthTest' => '1',
  ),
  'API_SECRET_KEY_SERVER' => '',
  'SOFT_NAME' => 'LiveOptical',
  'POWERED_BY_FRONTEND' => 'Powered by LiveOptical eCommerce for Opticians and Optometrists',
  'POWERED_BY_URL' => 'https://www.liveoptical.com/',
  'POWERED_BY_BACKEND' => '© <a href=\'https://www.liveoptical.com/\' target=\'_blank\'>LiveOptical</a>',
  'BACKEND_LOGO_SMALL' => 'upload/BACKEND_LOGO_SMALL-Newlogo3Small.jpg',
  'BACKEND_LOGIN_LOGO' => 'upload/BACKEND_LOGIN_LOGO-Newlogo3.jpg',
  'BACKEND_SHOW_HELP' => 0,
  'BACKEND_SHOW_FOOTER_LINKS' => 0,
  'MODULE_STATS_UPDATED' => 1452737450,
  'MODULE_STATS_NEED_UPDATING' => 0,
  'installedModules' => 
  array (
    'module.store-cloning' => true,
    'module.eye-exam' => true,
  ),
  'enabledModules' => 
  array (
    'module.store-cloning' => true,
    'module.eye-exam' => true,
  ),
  'SEARCH_MODELS' => '',
  'SEARCH_MODEL_PREVIEW' => 3,
  'SEARCH_MODEL_PER_PAGE' => 10,
  'ChronoPay_productid' => '',
  'ChronoPay_productname' => '',
  'ChronoPay_currency' => 'CAD',
  'SHIPPING_HANDLERS' => '',
  'DELIVERY_TAX' => 0,
  'DELIVERY_TAX_CLASS' => '',
  'FREE_SHIPPING_AUTO_RATE' => 1,
  'STORE_COUNTRY' => 'US',
  'STORE_STATE' => 'NY',
  'STORE_ZIP' => '',
  'STORE_CITY' => 'New York',
  'DEF_COUNTRY' => 'CA',
  'DEF_STATE' => 623,
  'CLONE_STORE_TYPE' => 'CLONE_STORE_CHILD',
  'CLONE_STORE_API_KEY' => 'Illumin34_98!',
  'ENABLE_VIRTUAL_MIRROR' => 1,
); ?>